pynac/pynac

pynac.pc.in
This is to deal with issue #14
=> Remove explicit SAGE_LOCAL from pynac.pc.in

m4/ax_python_devel.m4
python 3 prep: the current one seems to not be able to
properly find python 3
=> update to latest version of AX_PYTHON_DEVEL macro

ginac/inifcns_zeta.cpp
=> do not convert to numeric in zeta1_series

ginac/pseries.cpp
=> series: check for infinity after substitution in basis and exponent

ginac/inifcns_trans.cpp
=> reduce argument of exponential function by integer*2*pi*i

ginac/inifcns_trans.cpp, ginac/inifcns_trig.cpp
See #150; however: code still has to be tested.
=> expand difference after reducing period

ginac/inifcns.h, ginac/inifcns_hyperb.cpp
@rwst I have implemented arcsech into ginac functions. Please review it and suggest me if there is something more to add on or updated.
Thanks.
=> implemented arcsech into ginac functions

ginac/inifcns.h, ginac/inifcns_hyperb.cpp
Please review it and suggest if something needs to be changed. :)
=> implemented arccsch into ginac functions

ginac/symbol.cpp
Fixed the failing doctest. Please review. :) #144
=> fixed the failed doctest of issue #144 assume::posint

ginac/inifcns_trig.cpp
This tries to solve issue #146 . @rwst Please have a look at it and suggest if something more needs to be done!
=> simplified trig root expressions

ginac/inifcns_trig.cpp
@rwst Here is the new pull request with reference to #168 . Please have a look at it. :)
=> implemented reflection at pi/2 -(ref #168)

ginac/inifcns_hyperg.cpp
Same as #306.  I think this was the only other example.
=> One more PyBytes_ -> PyUnicode_ for Python 3

ginac/basic.h, ginac/ex.h, ginac/mpoly-singular.cpp
=> Use unordered_map in replace_with_symbol()

ginac/numeric.cpp
This updates `_mpz_pythonhash` for Python 3, and makes `_mpq_pythonhash`
consistent with hashes of rational numbers in Sage, like it used to be
the case. The implementation is copied from the current version of
[`sage.libs.gmp.pylong.mpz_pythonhash`](https://github.com/sagemath/sage/blob/a1e1a8f721fa32840968248200327af6a7f35de0/src/sage/libs/gmp/pylong.pyx#L99-L158).
See also https://trac.sagemath.org/ticket/28219.
=> update mpq and mpz pythonhash

ginac/numeric.cpp
This request is regarding [Sage trac #30446](https://trac.sagemath.org/ticket/30446). 
to Sage
This is the addition to Sage's doctests that I made:
[diff.txt](https://github.com/pynac/pynac/files/5362355/diff.txt)
=> Check for MPQ in the same fashion as MPZ in numeric::pow_int_exp

NEWS, README, acinclude.m4, ginac/basic.cpp, ginac/ex.cpp, ginac/ex.h, ginac/flags.h, ginac/function_info.cpp, ginac/inifcns_hyperb.cpp, ginac/inifcns_nstdsums.cpp, ginac/inifcns_trig.cpp, ginac/mul.cpp, ginac/order.cpp, m4/pkg.m4
=> some typos found by codespell

ginac/container.h
=> fix some compiler warnings

.gitignore, configure.ac, ginac/Makefile.am, ginac/archive.cpp, ginac/basic.h, ginac/mpoly-giac.cpp, ginac/mpoly-ginac.cpp, ginac/mpoly-singular.cpp, ginac/normal.cpp, ginac/upoly-ginac.cpp
... and do not conditionalize includes with HAVE_CONFIG_H
=> pynac-config.h: Move to ginac/, make it an installed header file

ginac/inifcns_trans.cpp
This is to fix the bug reported at
- [Sage Trac ticket 31739: Problem with exponential of arctanh and arcosh](https://trac.sagemath.org/ticket/31739)
This is my first contribution to pynac code (and to any C++ code).
Should tests be added somewhere?
Please review.
=> Fix exp of inverse hyperbolic functions

.github/workflows/ci-sage.yml, configure.ac
... to fix the failures on `ubuntu-trusty` as reported in https://trac.sagemath.org/ticket/31694
We also update the GH Actions workflow.
=> configure.ac: Test libraries with the C++ compiler

ginac/numeric.cpp
Otherwise, we fall back to a version of the code before #378, corrected so that it does not fall into the `abs` trap.
@DaveWitteMorris Does this look OK to you?
Portability tests are running at https://github.com/mkoeppe/pynac/actions/runs/980861323
=> ginac/numeric.cpp: Only use builtin for smull_overflow if supported
