- ginac/basic.h
- ginac/py_funcs.h
the python header directory (which often hasthe version number in it) is already in the include path
> fix include for python header

- configure.ac
- ginac/Makefile.am
The checks for gmp are moved before switching to `CXX` to avoid language problem as gmp is a plain `C` library. I initially selected `mpz_get_str` as one of the functions used by `pynac`, as it happens the real symbol is `__gmpz_get_str` the shorter name being an alias set up in headers.
> Add libgmp detection and automatic linking.

- ginac/inifcns_zeta.cpp
This implementation might not be the most efficient one (because the "manually constructed" series expansion is expanded once again).
Alternatively, the loop could go until `n < order` and the line
`ser += Order(pow(m-1, order))`
could be added before the return-statement. However, in this case the `options`-parameter isn't treated at all...
This is related to http://trac.sagemath.org/ticket/19836
> let zeta1_series produce the expansion with stieltjes-constants

- ginac/inifcns_trans.cpp
- ginac/inifcns_trig.cpp
This is a fix for the problems with the `exp` and `arctan` (same problem occurrs) in #123.
> replace is_equal comparions against Infinity and NegInfinity

- ginac/inifcns_trig.cpp
if possible, the argument passed to the trigonometric functions should be reduced according to the period length. this also enables the evaluation of expression containing assumed integers:
```
sage: var('k', domain='integer')
k
sage: sin(k*pi)
0
sage: cos(2*k*pi + pi/3)
1/2
```
and so on. Related to #130.
> improve evaluation of trigonometric functions

- ginac/function.cpp
Should the (now redundant) flag `expand_function_args = 0x0002` that triggered expansion of function arguments be deleted? It occurs at exactly one other place: in `flags.h`, where it is declared.
> always expand function arguments

- ginac/inifcns_trig.cpp
This fixes the inconsistent behavior of `cot(0)`. Also fixes the doctest failures caused by the rewriting of #162.
> return UnsignedInfinity at poles of trigonometric functions

- ginac/container.h
You should not use `/bits/algorithmfwd.h` in `ginac/container.h`. This is an internal header, see https://gcc.gnu.org/onlinedocs/gcc-4.6.2/libstdc++/api/a00749.html in particular at the very bottom:
```
This is an internal header file, included by other library headers. Do not attempt to use it directly. Instead, include <algorithm>.
```
I spotted this trying to compile `pynac` with clang on OS X.
> clean up header

- ginac/inifcns_trig.cpp
This change fixes Trac [21365](https://trac.sagemath.org/ticket/21365).
You'll know better than I if it creates other unexpected problems. Is there a reason cot() was being treated differently from sec() and csc() for floats?
> Update cot(float) to use inverse of tan()

- ginac/inifcns_orthopoly.cpp
There is nothing special about negative values of 'a'.
sage: gegenbauer(2,a,x)
2*(a + 1)*a*x^2 - a
sage: gegenbauer(2,-3,x)
12*x^2 + 3
sage: gegenbauer(120,-99/2,3)
1654502372608570682112687530178328494861923493372493824
Note that this patch also removes the requirement for 'a'
to be integer (when it is positive):
sage: gegenbauer(5,9/2,x)
21879/8*x^5 - 6435/4*x^3 + 1287/8*x
sage: gegenbauer(15,3/2,5)
3903412392243800
All these cases were checked with the results from Mathematica.
Signed-off-by: Carlos R. Mafra <crmafra@gmail.com>
> Support gegenbauer(n,a,x) with negative 'a'

- configure.ac
And upon successful detection add flint to the list of libraries to avoid underlinking.
> check for the presence of flint headers and library

- ginac/inifcns_zeta.cpp
When comparing the formula in https://en.wikipedia.org/wiki/Stieltjes_constants and the sage-output
```
sage: zeta(s).series(s==1, 2)
1*(s - 1)^(-1) + (euler_gamma) + (-1/2*stieltjes(1))*(s - 1) + Order((s - 1)^2)
```
we find that the formula in pynac is implemented incorrectly, as we divide by `(n+1)!` instead of `n!`. This is fixed within this PR.
> fix the incorrectly implemented formula for expansion around 1

- configure.ac
- ginac/Makefile.am
- pynac.pc.in
This branch uses `pkg-config` to find factory's include files and library. Since singular a `factory.pc` file is installed. While factory will likely bring `-lflint` I still added it to `pynac.pc.in` in case `factory` stop requiring it.
You may need development version of the `pkg-config` package to get `pkg.m4` which is needed to produce a correct `configure`.
> Switch factory detection to using pkg-config and flint to pynac.pc

- pynac.pc.in
If we link to giac, it should go in pynac.pc too.
> Add libgiac to pynac.pc

- ginac/inifcns_hyperg.cpp
I based the replacement to the one done in numeric.cpp.
> Add a macro for compatibility to python3 in inifcns_hyperg.cpp

- ginac/inifcns_hyperb.cpp
- ginac/inifcns_trig.cpp
The code here currently implements the simplifications `sin(I*something) --> I*sinh(something)` and `cos(I*something) --> cosh(something)`.
Performance probably is a bit worse (a call to `real_part` is needed, which is python/cython).
This should only be considered mergeable after the following TODOs are done:
> simplify trigonometric and hyperbolic functions with argument I*something

- ginac/numeric.cpp
There were several cases where the return value of `PyObject_RichCompareBool` was not checked for an error, and Python exceptions were being left uncleared in inappropriate places.
I'm not 100% sure about the changes in the comparison operators, but it makes sense to fix the `is_` methods.
> Improve error handling around PyObject_RichCompareBool

- ginac/numeric.cpp
Removed the `PyInt_` macro definitions on Python 3, since that only invites
errors (e.g. assuming that a PyLong object can be converted without overflow
to a C long).
> Some fixes to handling Python 3 long types

- ginac/numeric.cpp
This should use `PyUnicode_FromString` on Python 3, and `PyString_AsString` isn't used at all in this module.  This fixes numerous bugs in Sage on Python 3 like:
```
sage: arcsinh(z)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-fbfc0c968329> in <module>()
----> 1 arcsinh(z)
/home/embray/src/sagemath/sage-python3/local/lib/python3.6/site-packages/sage/symbolic/function.pyx in sage.symbolic.function.BuiltinFunction.__call__ (build/cythonized/sage/symbolic/function.cpp:11719)()
988
989             if callable(method):
--> 990                 res = method()
991
992         if res is None:
/home/embray/src/sagemath/sage-python3/local/lib/python3.6/site-packages/sage/symbol …
```
> Fix TypeError on Python 3

- ginac/numeric.cpp
Otherwise, in CentOS 6, log(-3) causes a segfault instead of returning nan
> Don't assume that a is positive in rational_power_parts

- ginac/numeric.cpp
See https://trac.sagemath.org/ticket/25979
> fix numeric::ratlog in the case where the argument is an MPZ type but the base is a LONG type

- ginac/useries.cpp
Depending how GMP is configured the macro from flint, `slong`, which actually
refers to GMP's `mp_limb_signed_t`, may be a `long long` instead of plain `long`.
`numeric` doesn't have a constructor for `long long`, leading to an ambiguous
overload error on the constructor.  In this case it should make more sense
to just use normal int and long types for these loop variables as it
makes sense to, and only cast to the "slong" type when passing to the
flint interface.
> Fix compliation error with GMP long long limbs.

- ginac/inifcns_trig.cpp
My complex analysis students found a sign error for the (symbolic) imaginary part of the cotangent.
The correct formula can be found [in the digital library of mathematical functions](https://dlmf.nist.gov/4.21#E40), where the imaginary part is given as
```math
\Im(\cot(z)) = \frac{- \sinh(2y)}{cosh(2y) - cos(2x)}.
```
> fix sign error in cot_imag_part

- configure.ac
Allow "configure --disable-maintainer-mode" to disable timestamp checking. Useful for building on clusters and other interesting platforms, in particular as a part of Sage.
> Allow "configure --disable-maintainer-mode"

- ginac/function.cpp
- ginac/numeric.cpp
This is required to fix deprecation warnings on unpickling with Python 3.8:
DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
> define PY_SSIZE_T_CLEAN

- ginac/container.h
- ginac/mpoly-giac.cpp
GCC warns that these calls to std::move() are pessimizing; see GCC's -Wpessimizing-move flag.  The calls prevent copy elision, by requiring that there be a copy to move from and a copy to move to.  See https://abseil.io/tips/11 for a good description of return value optimization.
> Remove pessimizing calls to std::move()

- ginac/numeric.cpp
As outlined in #356 and [Sage Trac #29156](https://trac.sagemath.org/ticket/29156), there is an issue with exponentiation where the exponent is negative and the numerator is greater than 32 bits. I just changed the function which throws an error if the numerator is greater than 32 bits to only do so when the numerator is greater than 64 bits (well, unless you've got some crazy old 32-bit system). Maybe this isn't the right fix, but it's at least doing more of what the method `numeric::to_long` is advertising. Here is a diff for a doctest addition:
[diff.txt](https://github.com/pynac/pynac/files/5398434/diff.txt)
> Actually check if result of division fits in long instead of in int

- .github/workflows/ci-sage.yml
- configure.ac
Adding a CI workflow using Sage.
In the first step, we build a source distribution. To make it work on Debian, we also modify `configure.ac` so that it falls back to Debian's renamed library `singular-factory` if `factory` cannot be found.  (This will also make Debian's patch https://salsa.debian.org/science-team/pynac/-/blob/master/debian/patches/find_singular.patch unnecessary.)
> Add CI workflow

- configure.ac
Given that Sage configures `pynac` using `--with-giac=no` and bug #341 is unresolved, we mark `--with-giac` as experimental and change its default from `check` to `no`.
> configure: Change default to --with-giac=no

- ginac/numeric.h
pynac doesn't currently compile with gcc-11 because of some changes in header handling. This PR adds one such header that now needs to be explicitly added.
The change should be compatible with other compilers, including older version of gcc.
> Add appropriate header for gcc11

- ginac/numeric.cpp
This is the pynac patch of trac ticket [#31585](https://trac.sagemath.org/ticket/31585) that fixes an overflow error in multiplication, division, and absolute value when working with long integers. The errors currently arise only on 32-bit machines, but that may change in the future (see trac ticket [#31986](https://trac.sagemath.org/ticket/31986)). Doctests are in the trac PR.
> 31585overflow32bit
